/**
 * Reporter render test — FIXTURE data, NO DB, ungated (runs in `npm run sim`). Proves
 * the HTML/MD generate correctly headless: 8 personas, inline SVG charts, coverage
 * matrix, PASS/FAIL, the #655 discrepancy, and a seed-stable body. The real report
 * (against the test DB) is generated by `npm run sim:report`.
 */
import { describe, it, expect } from "vitest";
import { EventLog } from "../event-log";
import { renderHtml, renderMd } from "./reporter";
import type { MonthPoint, RunResult } from "./types";

function fakeRun(
  persona: string,
  displayName: string,
  opts: { debt?: boolean; invest?: boolean; fail?: boolean } = {},
): RunResult {
  const log = new EventLog();
  log.record("event", "ingreso recibido (receivePartialIncome)", 101, { amount: 800_000, fn: "receiveIncome" });
  log.record("event", "gasto · Renta (createTransaction)", 102, { amount: 250_000, fn: "createTransaction" });
  log.record("event", "aporte a meta (addGoalContribution)", 103, { amount: 60_000, fn: "addGoalContribution" });
  if (opts.debt) log.record("event", "pago de deuda (addDebtPayment)", 104, { amount: 20_000, fn: "addDebtPayment" });
  if (opts.invest) log.record("event", "auto-DCA (ensureMonthlyContributions)", 128, { fn: "ensureMonthlyContributions" });
  log.record("event", "snapshot de patrimonio", 128, { fn: "snapshots" });

  log.check({ name: "liquidez · identidad del saco (cierre mes 1)", ok: true, detail: "saldo=1000000 esperado=1000000" });
  log.check({ name: "patrimonio · composición = liquidez + metas + inversiones − deudas", ok: true, detail: "ok" });
  log.check({ name: "evolución · velocidad patrimonial = neto(m) − neto(m−1)", ok: true, detail: "wv=200000" });
  if (opts.fail) log.check({ name: "flujo · algo se rompió", ok: false, detail: "real=1 esperado=2" });

  const series: MonthPoint[] = [
    { month: 1, netWorth: 1_000_000, liquidity: 500_000, portfolio: 400_000, goals: 100_000, debts: 0 },
    { month: 2, netWorth: 1_200_000, liquidity: 620_000, portfolio: 480_000, goals: 160_000, debts: 0 },
    { month: 3, netWorth: 1_450_000, liquidity: 700_000, portfolio: 560_000, goals: 240_000, debts: 0 },
  ];
  return { persona, displayName, series, log };
}

const runs: RunResult[] = [
  fakeRun("control-excelente", "Control Excelente", { debt: true }),
  fakeRun("sobreendeudado", "Sobreendeudado", { debt: true }),
  fakeRun("ingreso-muy-bajo", "Ingreso Muy Bajo", { debt: true }),
  fakeRun("ingresos-irregulares", "Ingresos Irregulares", { debt: true }),
  fakeRun("familia-metas-educacion", "Familia con Metas de Educación", { debt: true }),
  fakeRun("comprador-vivienda", "Comprador de Vivienda"),
  fakeRun("inversionista-activo", "Inversionista Activo"),
  fakeRun("inversionista-dca", "Inversionista DCA (cotizado)", { invest: true }),
];

describe("reporter · render headless (fixture, sin BD)", () => {
  it("el HTML trae las 8 personas, charts inline, matriz, PASS/FAIL y la sección #655", () => {
    const html = renderHtml(runs, { generatedAt: "2026-08-16T00:00:00.000Z" });
    for (const r of runs) expect(html, `falta ${r.displayName}`).toContain(r.displayName);
    expect(html).toContain("<polyline"); // charts SVG inline
    expect(html).toContain("Matriz de cobertura de features");
    expect(html).toContain("verde"); // status pill
    expect(html).toContain("#655"); // discrepancia conocida
    expect(html).toContain("<!doctype html>");
    // Autocontenido: sin CDN / red al abrirlo.
    expect(html).not.toMatch(/https?:\/\//);
  });

  it("mismo input → mismo HTML (seed-estable, sin generatedAt)", () => {
    expect(renderHtml(runs)).toBe(renderHtml(runs));
  });

  it("marca en rojo si hay fallas", () => {
    const withFail = [...runs.slice(0, 7), fakeRun("inversionista-dca", "Inversionista DCA (cotizado)", { invest: true, fail: true })];
    const html = renderHtml(withFail);
    expect(html).toContain("1 rojo");
  });

  it("el MD trae la tabla, los bugs y la conclusión", () => {
    const md = renderMd(runs);
    expect(md).toContain("| Persona | Meses | Checks");
    expect(md).toContain("Inversionista DCA (cotizado)");
    expect(md).toContain("#655");
    expect(md).toContain("## Conclusión");
    expect(md).toContain("0 fallas");
  });
});
